name: calil_api
description: Calil API with Dart
version: 0.3.5
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.2 <3.0.0'


dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0

dependencies:
  http: ^0.13.4
